name: breakout
dataset:
  name: atari-breakout
model:
  name: vae
  network: atari
  beta: 33
  latent_dim: 30
training:
  epochs: 300
---
name: breakout-large
dataset:
  name: atari-breakout
model:
  name: vae
  network: atari
  beta: 330
  latent_dim: 30
training:
  epochs: 500