name: breakout-vae
dataset:
  type: atari-breakout
model:
  type: vae
  network: atari
  beta: 33
  latent_dim: 30
training:
  epochs: 300
---
name: breakout-vae-medium
dataset:
  type: atari-breakout
model:
  type: vae
  network: atari
  beta: 60
  latent_dim: 30
training:
  epochs: 500
---
name: breakout-vae-large
dataset:
  type: atari-breakout
model:
  type: vae
  network: atari
  beta: 330
  latent_dim: 30
training:
  epochs: 500