name: dqn-cart
algorithm:
  type: dqn
  buffer_size: 50000
  total_timesteps: 100000
  training_start: 1000
  target_update_freq: 500
  exploration_fraction: 0.1
  lr: 5e-4
  gamma: 1.
  batch_size: 32
  clean_tensorboard_runs: True
  clean_previous_weights: True
environment:
  type: CartPole-v0

