name: vae-test
dataset:
  name: translation
model:
  name: vae
  beta: 30
  latent_dim: 5
training:
  epochs: 1
---
name: vae-dsprites
dataset:
  name: dsprites
model:
  name: vae
  beta: 35
  latent_dim: 5
training:
  epochs: 500
---
name: vae-duo
dataset:
  name: duo
model:
  name: vae
  beta: 35
  latent_dim: 10
training:
  epochs: 500
---
name: vae-duo-large
dataset:
  name: duo
model:
  name: vae
  beta: 100
  latent_dim: 10
training:
  epochs: 500
---
name: vae-duo-short
dataset:
  name: duo
model:
  name: vae
  beta: 35
  latent_dim: 10
training:
  epochs: 100
---
name: vae-trans
dataset:
  name: translation
model:
  name: vae
  beta: 30
  latent_dim: 5
training:
  epochs: 500
---
name: vae-trans-scale
dataset:
  name: translation_scale
model:
  name: vae
  beta: 30
  latent_dim: 5
training:
  epochs: 500
---
name: vae-trans-scale-short
dataset:
  name: translation_scale
model:
  name: vae
  beta: 30
  latent_dim: 5
training:
  epochs: 100
---
name: vae-large-latent
dataset:
  name: translation_scale
model:
  name: vae
  beta: 20
  latent_dim: 200
training:
  epochs: 500
---
name: vae-very-large-latent
dataset:
  name: translation_scale
model:
  name: vae
  beta: 8
  latent_dim: 1000
training:
  epochs: 500


